config/routes.rb
Rails.application.routes.draw do
  resources :runs
  resources :charities
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'sessions#index'

  get '/' => 'sessions#new'
  post '/' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  delete '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  get '/auth/:provider/callback' => 'sessions#omniauth'

  get '/welcome' => 'sessions#show'
  
  resources :users, only: [:index, :new, :create, :show]

  resources :runs

  resources :charities do 
    resources :runs, only: [:new, :index]
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/charity.rb
class Charity < ApplicationRecord

  has_many :runs
  has_many :users, through: :runs
  validates :name, presence: true, uniqueness: true
  validates :description, presence: true

  scope :alpha_order, -> { order(:name) }
  scope :top_three, -> { group(:name).order('distance DESC').limit(3) }
end

app/models/run.rb
class Run < ApplicationRecord
  
  belongs_to :user
  belongs_to :charity

  validates :distance, :duration, :charity_id, presence: true

  def charity_attributes=(attributes)
    self.charity = Charity.find_or_create_by(attributes) if !attributes['name'].empty?
    self.charity
  end

  def self.total_distance(user)
    where("user_id = ?", user.id).inject(0) { |sum, r| sum + r.distance } 
  end

  def self.total_amount_raised(user)
    where("user_id = ?", user.id).inject(0) { |sum, r| sum + r.distance * 3 }
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  
  has_many :runs
  has_many :charities, through: :runs
  validates :username, :email, presence: true
  validates :username, :email, uniqueness: true

  has_secure_password

  def self.from_omniauth(auth)
    where(email: auth.info.email).first_or_initialize do |user|
      user.username = auth.info.name
      user.email = auth.info.email
      user.password = SecureRandom.hex
    end
  end

  def self.total_charity_runs(charity)
    joins(:runs).group(:charity_id).where('charity_id = ?', charity.id).order('count(*)').pluck('username').first 
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?, :total_raised, :top_charities
  add_flash_types :danger

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def total_raised
    @user.runs.inject(0) { |sum, r| sum + r.distance * 3 }
  end

end

app/controllers/charities_controller.rb
class CharitiesController < ApplicationController

  def show
    @charity = Charity.find_by(id: params[:id])
  end

  def index
    @charities = Charity.alpha_order 
    @charity = Charity.new
  end

  def new
    @charity = Charity.new
  end

  def create
    @charity = Charity.new(charity_params) 
    if @charity.save
      redirect_to charity_path(@charity.id)
    else
      @charities = Charity.alpha_order
      render :index
    end
  end

  private

  def charity_params
    params.require(:charity).permit(:name, :description)
  end
end

app/controllers/runs_controller.rb
class RunsController < ApplicationController

  def index
    if @charity = Charity.find_by(id: params[:charity_id])
      @runs = @charity.runs
    else
      @runs = current_user.runs
    end
  end

  def show
    @run = Run.find_by(id: params[:id]) 
    redirect_to runs_path if !@run
  end

  def new
    @run = Run.new
    @run.build_charity
  end

  def create
    @run = Run.new(run_params)
    @run.user_id = current_user.id
    if @run.save
      redirect_to run_path(@run)
    else
      render :new
    end
  end

  def edit
    @run = Run.find_by(id: params[:id])
  end

  def update
    @run = Run.find_by(id: params[:id])
    @run.update(run_params)
    redirect_to run_path(@run)
  end

  def destroy
    @run = Run.find_by(id: params[:id])
    @run.delete
    redirect_to user_path(current_user)
  end

  private

  def run_params
    params.require(:run).permit(:distance, :duration, :location, :shoes, :notes, :charity_id, charity_attributes: [:name, :description])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def show

  end

  def index
    redirect_to user_path(current_user.id) if logged_in?
  end

  def new
  end

  def create
    @user = User.find_by(username: params[:user][:username])
    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to welcome_path
    else
      redirect_to root_path, danger: "Incorrect email or password"
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end

  def omniauth
    @user = User.from_omniauth(auth)
    @user.save
    session[:user_id] = @user.id
    redirect_to root_path
  end

  private

  def auth
    request.env['omniauth.auth']
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find_by(id: params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  private
  
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charities_helper.rb
module CharitiesHelper
end

app/helpers/runs_helper.rb
module RunsHelper

  #Helper method to edit runs. html_safe prevents Rails from escaping this string
  def user_edit_run(text, href)
    "<a href='#{href}'>#{text}</a>".html_safe
  end

  #Helper method to delet runs. html_safe prevents Rails from escaping this string
  #You could always test in the console to see what html a link_to generates, for example: helper.link_to "delete", "<url>", :method => 'delete'
  def user_delete_run(text, href, method)
    "<a data-method=\"delete\" href=\'#{href}\'>#{text}</a>".html_safe
  end
end

app/helpers/users_helper.rb
module UsersHelper
  
  def display_welcome_message
    if @user == current_user 
      tag.h2("Welcome, #{@user.username.capitalize}!", :class => "welcome-message")
    else
      tag.h2("Runner: #{@user.username.capitalize}", :class => "welcome-message")
    end
  end

end

app/views/charities/index.html.erb
<div class="container-fluid">
  <div class="container">
    <h2>Participating Charities</h2>
    <p>Our list continues to grow as runners add charities they are passionate about. If you've got a charity in mind that isn't listed, add it below!</p>

    <ul>
      <% @charities.each do |c| %>
        <li>
          <%= link_to c.name, charity_path(c.id), :class => "charity-name"  %><br>
          <%= c.description %>
        </li><br>
      <% end %>
    </ul>

    <h2>Add a New Charity</h2>

    <%= render partial: 'layouts/errors', locals: {object: @charity} %>

    <%= render partial: 'layouts/charity_form' %>
  </div>
</div>

app/views/charities/show.html.erb
<div class="container-fluid"> 
  <div class="container">
    <h2><%= @charity.name %></h2>

    <p><%= @charity.description %></p>

    <h3>Total Raised</h3>
    <p>$<%= @charity.runs.inject(0) {|sum, r| sum + r.distance * 4}%></p>

    <% !if @charity.runs.present? %>
    <h3>Top Runner</h3>

      <%= User.total_charity_runs(@charity) %>
      <p>Beat our top runner, and <%= link_to "add a run for the #{@charity.name}", new_charity_run_path(@charity) %>!</p>
    <% end %>

    <h3>Runs</h3>

    <% if !@charity.runs.present? %>

      <p>No runs yet! Be first to <%= link_to "add a run", new_charity_run_path(@charity) %>!<p>

    <% else %>

      <% @charity.runs.each do |r| %> 
        Distance: <%= r.distance %> miles - Raised: $<%= r.distance * 3 %> - Runner: <%= link_to r.user.username, user_path(r.user) %><br><br>
      <% end %>

      <%= link_to "View Runs", charity_runs_path(@charity), :class => 'boost-btn btn-primary btn-sm' %>&nbsp; <%= link_to "Add a Run", new_charity_run_path(@charity), :class => 'boost-btn btn-primary btn-sm' %>
      
    <% end %>
  </div>  
</div>

app/views/layouts/_charity_form.html.erb
<div class="charity-form">
  <%= form_for(@charity) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br><br>
    <%= f.label :description %>
    <%= f.text_area :description %><br><br>
    
    <%= f.submit "Add New Charity", :class => 'boost-btn btn-primary btn-sm' %>
  <% end %>
</div>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>

    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_run_form.html.erb
<p>
  <%= f.label :distance %> (miles):
  <%= f.number_field :distance %>
</p>
<p>
  <%= f.label :duration %> (mins):
  <%= f.number_field :duration %> 
</p>
<p>
  <%= f.label :location %>:
  <%= f.select :location, options_for_select(["Indoor", "Outdoor"]), :include_blank => "Select a location" %>
</p>
<p>
  <%= f.label :notes %>:
  <%= f.text_field :notes %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Boost - Run to Raise</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <% if logged_in? %>
    <nav class="navbar navbar-expand-lg navbar-light sticky-top">
      <a class="navbar-brand" href="/welcome">Boost</a>
      <span class="navbar-text">
          Donations made for every mile you run.
        </span>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav ml-auto">
          <li class="nav-link"><%= link_to "Add a Run", new_run_path %></li>
          <li class="nav-link"><%= link_to "Charities", charities_path %></li>
          <li class="nav-link"><%= link_to current_user.username.capitalize, user_path(current_user.id) %></li>
          <li class="nav-link"><%= link_to "Log Out", logout_path, method: :delete %></li>
        </ul>
      </div>
    </nav>
  <% end %>

  <body>
    <main>

          <%= yield %>
    
    </main>
  </body>
</html>

app/views/runs/edit.html.erb
<div class="container-fluid">
  <div class="container">
    <h2>Edit a Run</h2>

    <div>
      <%= form_for @run do |f| %>
        <%= render partial: 'layouts/run_form', locals: {f: f} %>

        <p>
          <%= f.label :charity %>:
            <%= f.collection_select(:charity_id, Charity.all, :id, :name, :include_blank => "Select a charity", :selected => @run.charity_id) %>
        </p>
        
        <p>
          <%= f.submit %>
        </p>

      <% end %>
    </div>
  </div>
</div>

app/views/runs/index.html.erb
<div class="container-fluid">
  <div class="container">
  <h2>Runs</h2>

  <% @runs.each do |r| %>
    <div>
      Runner: <%= r.user.username %><br>
      Charity: <%= link_to r.charity.name, charity_path(r.charity.id) %><br>
      Distance (miles): <%= r.distance %><br>
      Duration (mins): <%= r.duration %><br>
      Location: <%= r.location %><br>
      Notes: <%= r.notes %><br><br>
    </div>
  <% end %>
</div>

app/views/runs/new.html.erb
<div class="container-fluid"> 
  <div class="container"> 
    <h2>Add a Run</h2>

    <%= render partial: 'layouts/errors', locals: {object: @run} %>

    <div>
      <%= form_for(@run) do |f| %>
        <%= render partial: 'layouts/run_form', locals: {f: f} %>

        <p>
          <%= f.label :charity %>:
            <%= f.collection_select(:charity_id, Charity.all, :id, :name, :include_blank => "Select a charity", :selected => params[:charity_id])%>
        </p>


        <% if !params[:charity_id].present? %> 
          <p>Or add a new charity:</p>
          <p>
            <%=f.fields_for :charity do |c| %>
              <%= c.label :name %>:
              <%= c.text_field :name %><br><br>
              <%= c.label :description %>:
              <%= c.text_area :description %>
            <% end %>
          </p>
        <% end %>
        <p>
          <%= f.submit "Create Run", :class => 'boost-btn btn-primary btn-sm' %>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/runs/show.html.erb
<div class="container-fluid">
  <div class="container">
    <h2>Another run, another donation.</h2>
      <div>
      Charity: <%= link_to @run.charity.name, charity_path(@run.charity.id) %><br>
      Distance (miles): <%= @run.distance %><br>
      Duration (mins): <%= @run.duration %><br>
      Location: <%= @run.location %><br>

      <!-- Links showed on run's show using helper methods -->
      <%= user_edit_run 'Edit', edit_run_path(@run.id)%> | <%= user_delete_run 'Delete', run_path(@run), method: :delete %><br>
    
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div id="action-container">
  <div class="action">
    <h2>Sign Up!</h2>

    <%= render partial: 'layouts/errors', locals: {object: @user} %>

    <div>
      <%= form_for(@user) do |f| %>
        <p>
          <%= f.label :username %>
          <%= f.text_field :username %>
        </p>
        <p>
          <%= f.label :email %>
          <%= f.email_field :email %>
        </p>
        <p>
          <%= f.label :password %>
          <%= f.password_field :password %>
        </p>
        <p>
          <%= f.submit "Sign Up", :class => 'boost-btn btn-primary btn-sm btn-block' %>
        </p>
      <% end %>
    </div>
  </div>
  <p class="cta-section">Already a member? <%= link_to "Sign In", root_path %>.</a>
</div>

app/views/users/show.html.erb
<div class="container-fluid">
  <div class="container">
    <%= display_welcome_message %>

    <div class="row">
      <div class="col-md">
        <h3>All Runs</h3>
          <% @user.runs.each do |r| %>
            <div>
              Charity: <%= link_to r.charity.name, charity_path(r.charity.id) %><br>
              Distance (miles): <%= r.distance %><br>
              Duration (mins): <%= r.duration %><br>
              Location: <%= r.location %><br>
              Notes: <%= r.notes %> <br>
              Amount Raised: $<%= r.distance * 3 %> <br>

              <% if @user == current_user %>
              <!-- Links showed on user's show using helper methods -->
                <%= user_edit_run 'Edit', edit_run_path(r.id)%> | <%= user_delete_run 'Delete', run_path(r), method: :delete %>
              <% end %> 
              <br>
            </div>
          <% end %>
      </div>

    <div class="col-sm">
      <h3>Top Charities</h3>
        <% @user.charities.top_three.each do |c| %>
          Name: <%= c.name %> | 
          Total Distance: <%= c.runs.total_distance(@user) %>
          Total Raised: $<%= c.runs.total_amount_raised(@user) %><br><br>
        <% end %>

      <h3>Total Raised</h3>
      <p>$<%= total_raised %></p>
    </div>
  </div>
</div>